// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3wzv5djhscaLi5kM3v4aPROlYY8kX0Lw',
    appId: '1:211048511322:web:17de3e0e001be6fb526563',
    messagingSenderId: '211048511322',
    projectId: 'no-more-proxy-269a8',
    authDomain: 'no-more-proxy-269a8.firebaseapp.com',
    storageBucket: 'no-more-proxy-269a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyZohNsZyh24NqAAeDrgtG4acFDOu46Y4',
    appId: '1:211048511322:android:4d97da42026acd38526563',
    messagingSenderId: '211048511322',
    projectId: 'no-more-proxy-269a8',
    storageBucket: 'no-more-proxy-269a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSEhxJssvUR6qtMWg1bIXdVDff3wACb64',
    appId: '1:211048511322:ios:759dd9a01a2fee61526563',
    messagingSenderId: '211048511322',
    projectId: 'no-more-proxy-269a8',
    storageBucket: 'no-more-proxy-269a8.firebasestorage.app',
    iosBundleId: 'com.example.noproxy',
  );
}
